config/routes.rb
Rails.application.routes.draw do
  get 'characters/new'

  get 'chars_health/new'

  root 'main_pages#home'
  get 'changes' => 'main_pages#changes'
  get 'basics' => 'characters#basics'
  get 'universal' => 'characters#universal'
  get 'elements' => 'main_pages#elements'
  get 'mechanics' => 'main_pages#mechanics'
  get 'terms' => 'main_pages#terms'
  get 'ryu' => 'fighters#ryu'
  get 'kim' => 'fighters#kim'
  get 'evilryu' => 'fighters#eryu'
  get 'ken' => 'fighters#ken'
  get 'vken' => 'fighters#vken'
  get 'kyo' => 'fighters#kyo'
  get 'guile' => 'fighters#guile'
  get 'ryo' => 'fighters#ryo'
  get 'haggar' => 'fighters#haggar'
  get 'terry' => 'fighters#terry'
  get 'makoto' => 'fighters#makoto'
  get 'jin' => 'fighters#jin'
  get 'sakura' => 'fighters#sakura'
  get 'kazuya' => 'fighters#kazuya'
  get 'karin' => 'fighters#karin'
  get 'haohmaru' => 'fighters#haohmaru'
  get 'dan' => 'fighters#dan'
  get 'hibiki' => 'fighters#hibiki'
  get 'megaman' => 'fighters#megaman'
  get 'klonoa' => 'fighters#klonoa'
  get 'chun' => 'fighters#chun'
  get 'joe' => 'fighters#joe'
  get 'dudley' => 'fighters#dudley'
  get 'lucario' => 'fighters#lucario'
  get 'yang' => 'fighters#yang'
  get 'blaziken' => 'fighters#blaziken'
  get 'yun' => 'fighters#yun'
  get 'mario' => 'fighters#mario'
  get 'jill' => 'fighters#jill'
  get 'yoshi' => 'fighters#yoshi'
  get 'akuma' => 'fighters#akuma'
  get 'gengar' => 'fighters#gengar'
  get 'talbain' => 'fighters#talbain'
  get 'sonic' => 'fighters#sonic'
  get 'guy' => 'fighters#guy'
  get 'rock' => 'fighters#rock'
  get 'rolento' => 'fighters#rolento'
  get 'geese' => 'fighters#geese'
  get 'sagat' => 'fighters#sagat'
  get 'ryuji' => 'fighters#ryuji'
  get 'rose' => 'fighters#rose'
  get 'yuri' => 'fighters#yuri'
  get 'zangief' => 'fighters#zangief'
  get 'link' => 'fighters#link'
  get 'ibuki' => 'fighters#ibuki'
  get 'snake' => 'fighters#snake'
  get 'thawk' => 'fighters#thawk'
  get 'athena' => 'fighters#athena'
  get 'bison' => 'fighters#bison'
  get 'nakoruru' => 'fighters#nakoruru'
  get 'commando' => 'fighters#commando'
  get 'squall' => 'fighters#squall'
  get 'applejack' => 'fighters#applejack'
  get 'zero' => 'fighters#zero'
  get 'twilight' => 'fighters#twilight'
  get 'gouken' => 'fighters#gouken'
  get 'pinkie' => 'fighters#pinkie'
  get 'elena' => 'fighters#elena'
  get 'rarity' => 'fighters#rarity'
  get 'cammy' => 'fighters#cammy'
  get 'kula' => 'fighters#kula'
  get 'sonson' => 'fighters#sonson'
  get 'iori' => 'fighters#iori'
  get 'ingrid' => 'fighters#ingrid'
  get 'kyosuke' => 'fighters#kyosuke'
  get 'fluttershy' => 'fighters#fluttershy'
  get 'juri' => 'fighters#juri'
  get 'rainbow' => 'fighters#rainbow'
  get 'king' => 'fighters#king'
  get 'decapre' => 'fighters#decapre'
  get 'gardevoir' => 'fighters#gardevoir'
  get 'maki' => 'fighters#maki'
  get 'rugal' => 'fighters#rugal'
  get 'dhalsim' => 'fighters#dhalsim'
end

app/models/character.rb
class Character < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  helper_method :sort_column, :sort_direction
  def basics
    @characters = Character.order(sort_column + ' ' + sort_direction)
  end
  
  def universal
    @characters = Character.order(sort_column + ' ' + sort_direction)
  end
  
  private
  def sort_column
    Character.column_names.include?(params[:sort]) ? params[:sort] : "name"
  end
 
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/fighters_controller.rb
class FightersController < ApplicationController
  def ryu
  end

  def kim
  end

  def eryu
  end

  def ken
  end
  
  def vken
  end

  def kyo
  end
  
  def guile
  end

  def ryo
  end

  def haggar
  end

  def terry
  end

  def makoto
  end

  def jin
  end

  def sakura
  end

  def kazuya
  end

  def karin
  end

  def haohmaru
  end
  
  def dan
  end

  def hibiki
  end

  def megaman
  end
 
  def klonoa
  end

  def chun
  end

  def joe
  end

  def dudley
  end

  def lucario
  end

  def yang
  end

  def blaziken
  end

  def yun
  end

  def mario
  end

  def jill
  end

  def yoshi
  end

  
end

app/controllers/main_pages_controller.rb
class MainPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "VGFC"
    if page_title.empty?
      base_title
    else
      page_title + " - " + base_title
    end
  end
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/fighters_helper.rb
module FightersHelper
end

app/helpers/main_pages_helper.rb
module MainPagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/characters/basics.html.erb
<% provide(:title, "Basics") %>
<div id="FighterPage">

<h2 id="Char">The Game UI</h2>

<%= image_tag "info/matchsample.png" %>
<p>When playing a match in VGFC, there are several different meters on screen that you'll need to keep track of, in addition to your characters. This section will go into more detail on each of these different meters.</p>

<h2 id="Char">Health Meter</h2>

<p>This is the easiest one to identify, it's the large green meter at the top of the screen. When this meter is completely drained, your character is KO'd and you lose a round. The player to first reach the designated number of rounds wins that match. The number of rounds you play depends on the game mode you select; Normal/Honest is best of 2, Yolo is best of 5, and Teams is best of 3.</p>

<h3>Health Values</h3>

<p>Every character in the game has their own health value. This dictates how much damage a character can take before they're KO'd. So despite the health bars being the same length visually, not every character has the same health.</p>

<h2 id="Char">Stun Meter</h2>

<p>In addition to each character's health meter, each character also has a stun meter. As you get hit by attacks, this meter will fill up according to that attack's stun value (see each character's page for info on how much stun each attack deals). Once this meter is full, your character will fall dizzy. A character that falls dizzy is invincible until they get up again, at which point they're stuck in the dizzy state for an extended period; characters are completely vulnerable while dizzy.</p>

<p>The dizzy meter doesn't increase when you block, but it does stop decreasing in this instance. In order to get the stun meter to start draining, you have to avoid coming in contact with any attacks for at least one second, at which point it will start draining very slowly.</p>

<p>Below you can find a table listing every character's health and stun values; you can click on the headers to sort it by each category. Note that, much like the health meter, each character has different stun values (so some get dizzy easier than others).</p>

<table class="DataTable">
  <tr>
    <th><%= sortable "name", "Character Name" %></th>
    <th><%= sortable "health", "Character Health" %></th>
    <th><%= sortable "stun", "Character Stun" %></th>
  </tr>
  <% for character in @characters %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.health %></td>
    <td><%= character.stun %></td>
  </tr>
  <% end %>
</table>

<h2 id="Char">Guard Meter</h2>

<p>Next to the stun meter is another bar, the guard meter. Unlike the health and stun meters, every character has a value of 1000 for their guard meter. Every time you block an attack, unless that attack is a light attack, it increases this meter by an amount equal to the strength of the opponent's attack (with a few exceptions). If an attack causes this meter to fill up, you will enter a guard crush state; your character will crumple and you will be completely vulnerable for a while. Much like the stun meter, the guard meter will only start draining if you avoid coming into contact with other moves for about a second, and stops draining if you get hit or block an attack.</p>

<h2 id="Char">Super Meter</h2>

<p>This is an important meter, as it's the meter that gives you access to all of your EX and Super moves. It's divided into 3 sections; you can have a maximum of 1200 points worth of Super Meter, and each individual section is worth 400 points. In each character's frame data you can see how much meter a move builds or requires; 400 points for one bar, 800 points for two and 1200 points for three.</p>

<p>You start out every match with no super meter, but this meter is carried over between rounds. You build meter by attacking or getting attacked; you get the most meter from actually hitting the opponent, but you also get some meter from having your attacks blocked, getting hit yourself, blocking your opponents attacks, or just performing moves (other than light attacks).</p>

<h2 id="Char">Ultra Meter</h2>

<p>Another bar next to your super meter. This serves only one purpose; to perform Ultra combos. The only way to build this meter is by dealing damage. Once this meter is at least halfway full, you are able to perform an Ultra combo.</p>

<p>The value of Ultras are equal to the total life your opponent has. So when fighting Ryu, who has 1000 health, you need to deal 500 damage total in order to be able to perform your Ultra combo. If you're fighting Yun, who has 850 health, you only need to deal 425 damage.</p>

<h2 id="Char">The Timer</h2>

<p>The large numbers in between each health bar. It's pretty simple; it counts down every second, and once it hits zero, the game ends. The player that has the highest percentage of life left at this point wins that round.</p>

<p>So, for example, Zangief is fighting Megaman. Zangief has 350HP left while Megaman has 300HP. 350/1100 = 31.8%, 300/900=33.3%. So even though Zangief has more life left total, Megaman has the highest percentage of life left, so Megaman will win that round.</p>

<p>In any case that both players have the same percentage of life left, both players will lose that round. If it's the final round and this happens, the match will end in a draw.</p>

</div>

app/views/fighters/blaziken.html.erb
<% provide(:title, "Blaziken") %>
<div id="FighterPage">
<h1 id="Name">Blaziken</h1>
<%= image_tag "blaziken/bust.png", :class => "FighterImg" %>
<p class="Bio">TBW</p>
<div class="MainInfo">
<h2 id="Basics">The Basics</h2>
<p>TBW</p>
<h2 id="MoveInfo">Move Info</h2>

<%= render 'layouts/fighters/zemp' %>

<h2 id="FrameData">Frame Data</h2>

<%= render 'layouts/fighters/zemp' %>

</div>
</div>

app/views/fighters/cammy.html.erb
<% provide(:title, "Cammy") %>
<div id="FighterPage">
<h1 id="Name">Cammy</h1>
<%= image_tag "cammy/bust.png", :class => "FighterImg" %>
<p class="Bio">TBW</p>
<div class="MainInfo">
<h2 id="Basics">The Basics</h2>
<p>TBW</p>
<h2 id="MoveInfo">Move Info</h2>

<%= render 'layouts/fighters/zemp' %>

<h2 id="FrameData">Frame Data</h2>

<%= render 'layouts/fighters/zemp' %>

</div>
</div>

app/views/fighters/elena.html.erb
<% provide(:title, "Elena") %>
<div id="FighterPage">
<h1 id="Name">Elena</h1>
<%= image_tag "elena/bust.png", :class => "FighterImg" %>
<p class="Bio">TBW</p>
<div class="MainInfo">
<h2 id="Basics">The Basics</h2>
<p>TBW</p>
<h2 id="MoveInfo">Move Info</h2>

<%= render 'layouts/fighters/zemp' %>

<h2 id="FrameData">Frame Data</h2>

<%= render 'layouts/fighters/zemp' %>

</div>
</div>

app/views/fighters/gouken.html.erb
<% provide(:title, "Gouken") %>
<div id="FighterPage">
<h1 id="Name">Gouken</h1>
<%= image_tag "gouken/bust.png", :class => "FighterImg" %>
<p class="Bio">TBW</p>
<div class="MainInfo">
<h2 id="Basics">The Basics</h2>
<p>TBW</p>
<h2 id="MoveInfo">Move Info</h2>

<%= render 'layouts/fighters/zemp' %>

<h2 id="FrameData">Frame Data</h2>

<%= render 'layouts/fighters/zemp' %>

</div>
</div>

app/views/fighters/kyosuke.html.erb
<% provide(:title, "Kyosuke") %>
<div id="FighterPage">
<h1 id="Name">Kyosuke</h1>
<%= image_tag "kyosuke/bust.png", :class => "FighterImg" %>
<p class="Bio">TBW</p>
<div class="MainInfo">
<h2 id="Basics">The Basics</h2>
<p>TBW</p>
<h2 id="MoveInfo">Move Info</h2>

<%= render 'layouts/fighters/zemp' %>

<h2 id="FrameData">Frame Data</h2>

<%= render 'layouts/fighters/zemp' %>

</div>
</div>

app/views/fighters/lucario.html.erb
<% provide(:title, "Lucario") %>
<div id="FighterPage">
<h1 id="Name">Lucario</h1>
<%= image_tag "lucario/bust.png", :class => "FighterImg" %>
<p class="Bio">TBW</p>
<div class="MainInfo">
<h2 id="Basics">The Basics</h2>
<p>TBW</p>
<h2 id="MoveInfo">Move Info</h2>

<%= render 'layouts/fighters/lucariomoves' %>

<h2 id="FrameData">Frame Data</h2>

<%= render 'layouts/fighters/lucarioframes' %>

</div>
</div>

app/views/layouts/_characters.html.erb
<div id="characters">
  <div class="charnames1">
  <ul>
  <li><%= link_to "Ryu", ryu_path, :class => "mainlink" %></li>
  <li><%= link_to "Ken", ken_path, :class => "mainlink" %> </li>
  <li><%= link_to "Guile", guile_path, :class => "mainlink" %> </li>
  <li><%= link_to "Mike Haggar", haggar_path, :class => "mainlink" %> </li>
  <li><%= link_to "Makoto", makoto_path, :class => "mainlink" %> </li>
  <li><%= link_to "Sakura", sakura_path, :class => "mainlink" %> </li>
  <li><%= link_to "Karin", karin_path, :class => "mainlink" %> </li>
  <li><%= link_to "Dan", dan_path, :class => "mainlink" %> </li>
  <li><%= link_to "Megaman", megaman_path, :class => "mainlink" %> </li>
  <li><%= link_to "Chun-li", chun_path, :class => "mainlink" %> </li>
  <li><%= link_to "Dudley", dudley_path, :class => "mainlink" %> </li>
  <li><%= link_to "Yang", yang_path, :class => "mainlink" %> </li>
  <li><%= link_to "Yun", yun_path, :class => "mainlink" %> </li>
  <li><%= link_to "Jill Valentine", jill_path, :class => "mainlink" %> </li>
  <li><%= link_to "Akuma", akuma_path, :class => "mainlink" %> </li>
  <li><%= link_to "Jon Talbain", talbain_path, :class => "mainlink" %></li>
  </ul>
  </div>
  <div class="charnames2">
  <li><%= link_to "Guy", guy_path, :class => "mainlink" %> </li>
  <li><%= link_to "Rolento", rolento_path, :class => "mainlink" %> </li>
  <li><%= link_to "Sagat", sagat_path, :class => "mainlink" %> </li>
  <li><%= link_to "Rose", rose_path, :class => "mainlink" %> </li>
  <li><%= link_to "Zangief", zangief_path, :class => "mainlink" %> </li>
  <li><%= link_to "Ibuki", ibuki_path, :class => "mainlink" %> </li>
  <li><%= link_to "T. Hawk", thawk_path, :class => "mainlink" %> </li>
  <li><%= link_to "M. Bison", bison_path, :class => "mainlink" %> </li>
  <li><%= link_to "C. Commando", commando_path, :class => "mainlink" %> </li>
  <li><%= link_to "Zero", zero_path, :class => "mainlink" %> </li>
  <li><%= link_to "Gouken", gouken_path, :class => "mainlink" %> </li>
  <li><%= link_to "Elena", elena_path, :class => "mainlink" %> </li>
  <li><%= link_to "Cammy", cammy_path, :class => "mainlink" %> </li>
  <li><%= link_to "SonSon", sonson_path, :class => "mainlink" %> </li>
  <li><%= link_to "Ingrid", ingrid_path, :class => "mainlink" %> </li>
  <li><%= link_to "Kyosuke", kyosuke_path, :class => "mainlink" %> </li>
  </div>
  <div class="charnames3">
  <li><%= link_to "Decapre", decapre_path, :class => "mainlink" %> </li>
  <li><%= link_to "Juri", juri_path, :class => "mainlink" %> </li>
  <li><%= link_to "Maki", maki_path, :class => "mainlink" %> </li>
  <li><%= link_to "Dhalsim", dhalsim_path, :class => "mainlink" %> </li>
  <li><%= link_to "Kim", kim_path, :class => "mainlink" %> </li>
  <li><%= link_to "Kyo", kyo_path, :class => "mainlink" %> </li>
  <li><%= link_to "Ryo", ryo_path, :class => "mainlink" %> </li>
  <li><%= link_to "Terry", terry_path, :class => "mainlink" %> </li>
  <li><%= link_to "Jin", jin_path, :class => "mainlink" %> </li>
  <li><%= link_to "Kazuya", kazuya_path, :class => "mainlink" %> </li>
  <li><%= link_to "Haohmaru", haohmaru_path, :class => "mainlink" %> </li>
  <li><%= link_to "Hibiki", hibiki_path, :class => "mainlink" %> </li>
  <li><%= link_to "Klonoa", klonoa_path, :class => "mainlink" %> </li>
  <li><%= link_to "Joe", joe_path, :class => "mainlink" %> </li>
  <li><%= link_to "Lucario", lucario_path, :class => "mainlink" %> </li>
  <li><%= link_to "Blaziken", blaziken_path, :class => "mainlink" %> </li>
  </div>
  <div class="charnames4">
  <li><%= link_to "Mario", mario_path, :class => "mainlink" %> </li>
  <li><%= link_to "Yoshi", yoshi_path, :class => "mainlink" %> </li>
  <li><%= link_to "Gengar", gengar_path, :class => "mainlink" %> </li>
  <li><%= link_to "Sonic", sonic_path, :class => "mainlink" %> </li>
  <li><%= link_to "Rock Howard", rock_path, :class => "mainlink" %> </li>
  <li><%= link_to "Geese Howard", geese_path, :class => "mainlink" %> </li>
  <li><%= link_to "Ryuji", ryuji_path, :class => "mainlink" %> </li>
  <li><%= link_to "Yuri", yuri_path, :class => "mainlink" %> </li>
  <li><%= link_to "Link", link_path, :class => "mainlink" %> </li>
  <li><%= link_to "Snake", snake_path, :class => "mainlink" %> </li>
  <li><%= link_to "Athena", athena_path, :class => "mainlink" %> </li>
  <li><%= link_to "Nakoruru", nakoruru_path, :class => "mainlink" %> </li>
  <li><%= link_to "Squall", squall_path, :class => "mainlink" %> </li>
  <li><%= link_to "Applejack", applejack_path, :class => "mainlink" %> </li>
  <li><%= link_to "Twilight Sparkle", twilight_path, :class => "mainlink" %> </li>
  <li><%= link_to "Pinkie Pie", pinkie_path, :class => "mainlink" %> </li>
  </div>
  <div class="charnames5">
  <li><%= link_to "Rarity", rarity_path, :class => "mainlink" %> </li>
  <li><%= link_to "Kula", kula_path, :class => "mainlink" %> </li>
  <li><%= link_to "Iori", iori_path, :class => "mainlink" %> </li>
  <li><%= link_to "Rainbow Dash", rainbow_path, :class => "mainlink" %> </li>
  <li><%= link_to "Fluttershy", fluttershy_path, :class => "mainlink" %> </li>
  <li><%= link_to "King", king_path, :class => "mainlink" %> </li>
  <li><%= link_to "Gardevoir", gardevoir_path, :class => "mainlink" %> </li>
  <li><%= link_to "Rugal", rugal_path, :class => "mainlink" %> </li>
  </div>

<table>
<tr>
  <th></th>
  <th><%= link_to image_tag("megaman.png", alt: "Megaman"), megaman_path %></th>
  <th><%= link_to image_tag("zero.png", alt: "Zero"), zero_path %></th>
  <th><%= link_to image_tag("talbain.png", alt: "Talbain"), talbain_path %></th>
  <th><%= link_to image_tag("rarity.png", alt: "Rarity"), rarity_path %></th>
  <th><%= link_to image_tag("pinkie.png", alt: "Pinkie"), pinkie_path %></th>
  <th><%= link_to image_tag("fluttershy.png", alt: "Fluttershy"), fluttershy_path %></th>
  <th></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("jill.png", alt: "Jill"), jill_path %></th>
  <th><%= link_to image_tag("commando.png", alt: "Commando"), commando_path %></th>
  <th><%= link_to image_tag("sonson.png", alt: "Sonson"), sonson_path %></th>
  <th><%= link_to image_tag("twilight.png", alt: "Twilight"), twilight_path %></th>
  <th><%= link_to image_tag("applejack.png", alt: "Applejack"), applejack_path %></th>
  <th><%= link_to image_tag("rainbow.png", alt: "Rainbow"), rainbow_path %></th>
  <th></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("haggar.png", alt: "Haggar"), haggar_path %></th>
  <th><%= link_to image_tag("maki.png", alt: "Maki"), maki_path %></th>
  <th><%= link_to image_tag("guy.png", alt: "Guy"), guy_path %></th>
  <th><%= link_to image_tag("blaziken.png", alt: "Blaziken"), blaziken_path %></th>
  <th><%= link_to image_tag("gardevoir.png", alt: "Gardevoir"), gardevoir_path %></th>
  <th><%= link_to image_tag("gengar.png", alt: "Gengar"), gengar_path %></th>
  <th></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("ingrid.png", alt: "Ingrid"), ingrid_path %></th>
  <th><%= link_to image_tag("sakura.png", alt: "Sakura"), sakura_path %></th>
  <th><%= link_to image_tag("rolento.png", alt: "Rolento"), rolento_path %></th>
  <th><%= link_to image_tag("mario.png", alt: "Mario"), mario_path %></th>
  <th><%= link_to image_tag("link.png", alt: "Link"), link_path %></th>
  <th><%= link_to image_tag("lucario.png", alt: "Lucario"), lucario_path %></th>
  <th></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("karin.png", alt: "Karin"), karin_path %></th>
  <th><%= link_to image_tag("dan.png", alt: "Dan"), dan_path %></th>
  <th><%= link_to image_tag("rose.png", alt: "Rose"), rose_path %></th>
  <th><%= link_to image_tag("klonoa.png", alt: "Klonoa"), klonoa_path %></th>
  <th><%= link_to image_tag("sonic.png", alt: "Sonic"), sonic_path %></th>
  <th><%= link_to image_tag("yoshi.png", alt: "Yoshi"), yoshi_path %></th>
  <th></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("chun.png", alt: "Chun-li"), chun_path %></th>
  <th><%= link_to image_tag("ken.png", alt: "Ken"), ken_path %></th>
  <th><%= link_to image_tag("ryu.png", alt: "Ryu"), ryu_path %></th>
  <th><%= link_to image_tag("kyo.png", alt: "Kyo"), kyo_path %></th>
  <th><%= link_to image_tag("kim.png", alt: "Kim"), kim_path %></th>
  <th><%= link_to image_tag("terry.png", alt: "Terry"), terry_path %></th>
  <th></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("cammy.png", alt: "Cammy"), cammy_path %></th>
  <th><%= link_to image_tag("sagat.png", alt: "Sagat"), sagat_path %></th>
  <th><%= link_to image_tag("guile.png", alt: "Guile"), guile_path %></th>
  <th><%= link_to image_tag("joe.png", alt: "Joe"), joe_path %></th>
  <th><%= link_to image_tag("athena.png", alt: "Athena"), athena_path %></th>
  <th><%= link_to image_tag("ryo.png", alt: "Ryo"), ryo_path %></th>
  <th></th>
</tr>
<tr>
  <th><%= link_to image_tag("decapre.png", alt: "Decapre"), decapre_path %></th>
  <th><%= link_to image_tag("juri.png", alt: "Juri"), juri_path %></th>
  <th><%= link_to image_tag("hawk.png", alt: "T. Hawk"), thawk_path %></th>
  <th><%= link_to image_tag("zangief.png", alt: "Zangief"), zangief_path %></th>
  <th><%= link_to image_tag("ryuji.png", alt: "Ryuji"), ryuji_path %></th>
  <th><%= link_to image_tag("rock.png", alt: "Rock"), rock_path %></th>
  <th><%= link_to image_tag("geese.png", alt: "Geese"), geese_path %></th>
  <th><%= link_to image_tag("rugal.png", alt: "Rugal"), rugal_path %></th>
</tr>
<tr>
  <th><%= link_to image_tag("kyosuke.png", alt: "Kyosuke"), kyosuke_path %></th>
  <th><%= link_to image_tag("gouken.png", alt: "Gouken"), gouken_path %></th>
  <th><%= link_to image_tag("akuma.png", alt: "Akuma"), akuma_path %></th>
  <th><%= link_to image_tag("bison.png", alt: "Bison"), bison_path %></th>
  <th><%= link_to image_tag("squall.png", alt: "Squall"), squall_path %></th>
  <th><%= link_to image_tag("snake.png", alt: "Snake"), snake_path %></th>
  <th><%= link_to image_tag("yuri.png", alt: "Yuri"), yuri_path %></th>
  <th><%= link_to image_tag("iori.png", alt: "Iori"), iori_path %></th>
</tr>
<tr>
  <th><%= link_to image_tag("dhalsim.png", alt: "Dhalsim"), dhalsim_path %></th>
  <th><%= link_to image_tag("dudley.png", alt: "Dudley"), dudley_path %></th>
  <th><%= link_to image_tag("yun.png", alt: "Yun"), yun_path %></th>
  <th><%= link_to image_tag("yang.png", alt: "Yang"), yang_path %></th>
  <th><%= link_to image_tag("jin.png", alt: "Jin"), jin_path %></th>
  <th><%= link_to image_tag("kazuya.png", alt: "Kazuya"), kazuya_path %></th>
  <th><%= link_to image_tag("kula.png", alt: "Kula"), kula_path %></th>
  <th><%= link_to image_tag("king.png", alt: "King"), king_path %></th>
</tr>
<tr>
  <th></th>
  <th><%= link_to image_tag("elena.png", alt: "Elena"), elena_path %></th>
  <th><%= link_to image_tag("ibuki.png", alt: "Ibuki"), ibuki_path %></th>
  <th><%= link_to image_tag("makoto.png", alt: "Makoto"), makoto_path %></th>
  <th><%= link_to image_tag("haohmaru.png", alt: "Haohmaru"), haohmaru_path %></th>
  <th><%= link_to image_tag("nakoruru.png", alt: "Nakoruru"), nakoruru_path %></th>
  <th><%= link_to image_tag("hibiki.png", alt: "Hibiki"), hibiki_path %></th>
  <th></th>
</tr>
</table>
</div>